"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
# from logging import config
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
DEBUG = os.getenv("DEBUG")

FRONTEND_URL = os.getenv("FRONTEND_URL")
FRONTEND_DEV_URL = os.getenv("FRONTEND_DEV_URL")
BACKEND_URL = os.getenv("BACKEND_URL")
BACKEND_DEV_URL = os.getenv("BACKEND_DEV_URL")
LOCALHOST = os.getenv("LOCALHOST")

ALLOWED_HOSTS = [BACKEND_DEV_URL, BACKEND_URL, LOCALHOST,]

# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "django_filters",

    # Your apps
    "accounts",
    "attendance",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

AUTH_USER_MODEL = "accounts.User"


# REST Framework 
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
}

# JWT 
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME":  timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS":  True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# CORS 
CORS_ALLOWED_ORIGINS = [FRONTEND_DEV_URL, FRONTEND_URL,]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [FRONTEND_DEV_URL, FRONTEND_URL,]

# ─────────────────────────────────────────────
# UNFOLD ADMIN
# ─────────────────────────────────────────────
UNFOLD = {
    "SITE_TITLE": "ScanOva Examination Attendance System",
    "SITE_HEADER": "ScanOva",
    "COLORS": {
    "base": {
        # Zinc — neutral grays used across the UI
        "50":  "oklch(98.5% 0.001 286)",
        "100": "oklch(96.7% 0.001 286)",
        "200": "oklch(92.8% 0.003 286)",
        "300": "oklch(87.0% 0.005 286)",
        "400": "oklch(70.7% 0.011 286)",
        "500": "oklch(55.1% 0.014 286)",
        "600": "oklch(44.6% 0.015 286)",
        "700": "oklch(37.3% 0.013 286)",
        "800": "oklch(27.8% 0.011 286)",
        "900": "oklch(21.0% 0.011 286)",
        "950": "oklch(13.0% 0.007 286)",
    },
    "primary": {
        # Teal — matches --primary in your globals.css
        "50":  "oklch(98.2% 0.018 196)",
        "100": "oklch(95.2% 0.051 194)",
        "200": "oklch(90.5% 0.093 192)",
        "300": "oklch(84.4% 0.143 189)",
        "400": "oklch(77.7% 0.153 185)",
        "500": "oklch(72.0% 0.132 183)",   # teal-500 — dark mode --primary
        "600": "oklch(64.9% 0.116 181)",
        "700": "oklch(56.6% 0.097 180)",   # teal-700 — light mode --primary
        "800": "oklch(47.5% 0.079 180)",
        "900": "oklch(40.6% 0.066 180)",
        "950": "oklch(27.9% 0.053 185)",
    },
    "font": {
        "subtle-light":    "var(--color-base-500)",   # muted text on light bg
        "subtle-dark":     "var(--color-base-400)",   # muted text on dark bg
        "default-light":   "var(--color-base-600)",   # body text on light bg
        "default-dark":    "var(--color-base-300)",   # body text on dark bg
        "important-light": "var(--color-base-900)",   # headings on light bg
        "important-dark":  "var(--color-base-100)",   # headings on dark bg
    },
},
}