# Generated by Django 6.0.2 on 2026-03-01 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('expected_students', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('closed', 'Closed')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to='attendance.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to='attendance.level')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to='attendance.program')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='attendance.level'),
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='attendance.program'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('qr_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='attendance.level')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='attendance.program')),
            ],
            options={
                'ordering': ['index_number'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('A', 'Section A – Objective'), ('B', 'Section B – Theory')], max_length=1)),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('duplicate', 'Duplicate'), ('invalid', 'Invalid')], default='present', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.examsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='attendance.student')),
            ],
            options={
                'ordering': ['scan_time'],
            },
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['status'], name='attendance__status_ccf5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['date'], name='attendance__date_904ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['qr_code'], name='attendance__qr_code_c819c9_idx'),
        ),
        migrations.AddIndex(
            model_name='examattendance',
            index=models.Index(fields=['exam_session', 'section'], name='attendance__exam_se_fa3079_idx'),
        ),
        migrations.AddIndex(
            model_name='examattendance',
            index=models.Index(fields=['scan_time'], name='attendance__scan_ti_d47e13_idx'),
        ),
        migrations.AddIndex(
            model_name='examattendance',
            index=models.Index(fields=['status'], name='attendance__status_66479b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examattendance',
            unique_together={('student', 'exam_session', 'section')},
        ),
    ]
