# Generated by Django 6.0.2 on 2026-03-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='attendance__qr_code_c819c9_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qr_code',
        ),
    ]
