# Generated by Django 6.0.2 on 2026-03-22 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_student_attendance__qr_code_c819c9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='examattendance',
            name='attendance__scan_ti_d47e13_idx',
        ),
        migrations.RemoveIndex(
            model_name='examattendance',
            name='attendance__status_66479b_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='attendance.level'),
        ),
        migrations.AddIndex(
            model_name='examattendance',
            index=models.Index(fields=['student'], name='attendance__student_a1f889_idx'),
        ),
    ]
